name: expendria
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  sqflite: ^2.3.3+1
  path: ^1.9.0


  math_expressions: ^2.5.0
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # Added this package

flutter:
  uses-material-design: true
  assets:
    - assets/14485905_5475310.jpg
    - assets/logo.png # Assuming your logo file is named logo.png

# Added this entire section at the bottom
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
